### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by T8star1984** [choey/Comfy-Topaz#1]
![QQ图片20240413002627](https://github.com/choey/Comfy-Topaz/assets/161950228/d8811a0e-8c08-4c8c-a7f6-64355cff2940)
hi,it is stop at this node

**Comment by choey** [comment]
What do you see in ComfyUI logs? Look for lines starting with `Comfy-Topaz:`

**Comment by nftlaolong** [comment]
![screenshot-20240418-155740](https://github.com/choey/Comfy-Topaz/assets/112178483/7fc1e639-3508-4a59-907e-8705392035d6)
 
is stop at this node,Maybe I need to pay for him?

**Comment by choey** [comment]
I'm not sure why that happens, but yes--you do need a licensed copy of Topaz Photo AI (run the app first and log in), before you can start using `tpai.exe`. Please reopen if this happens after logging in successfully.
